language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8
script:
  - xcodebuild -workspace Postal.xcworkspace -scheme Postal-iOS -sdk iphonesimulator build
  - xcodebuild -workspace Postal.xcworkspace -scheme Postal-macOS -sdk macosx build
