matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - xctool -workspace Postal.xcworkspace -scheme Postal-iOS -sdk iphonesimulator build
  - xctool -workspace Postal.xcworkspace -scheme Postal-macOS -sdk macosx build
